[package]
name = "everdrive-loader"
version = "0.1.0"
authors = ["Carsten Elton Sorensen <csoren@gmail.com>"]
description = "Mega Everdrive X3/5/7 interface"

[dependencies]
clap = "~2.32.0"
toml = "0.4.0"
serde = "1.0"
serde_derive = "1.0"
dirs = "1.0.4"
serial = "0.4"
